### ISSUE TITLE
 Received physics frame update for ship with ShipId: xxx, but a ship with this ShipId does not exist

### ISSUE THREAD

**Issue by krody2333** [ValkyrienSkies/Valkyrien-Skies-2#1020]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Forge

### Issue description

After using delete "my ship name", the backend shows  "Received physics frame update for ship with ShipId: xxx, but a ship with this ShipId does not exist" it

### Issue reproduction

The ship has been deleted, but the physical frame is still present.

### Logs

[debug.log](https://github.com/user-attachments/files/18117041/debug.log)
[latest.log](https://github.com/user-attachments/files/18117043/latest.log)

**Comment by stiggy1001** [comment]
Can we get some movement on this one, it is basically server destroying

**Comment by PriestOfFerns** [comment]
@stiggy1001 I've never heard of this happening on ship delete, but this is a common old interactive issue and has been fixed both by vmod and interactive's nightlies.

**Comment by stiggy1001** [comment]
@PriestOfFerns thanks for the fast response, i did have interactive installed, it had been removed but now its causing this issue, any thoughts on how to fix it post interactive?

**Comment by PriestOfFerns** [comment]
@stiggy1001 install vmod, it deletes empty ships

**Comment by BezimyanniyDSM** [comment]
I get this error if I run any mechanism from create

**Comment by sleepsemek** [comment]
+1 on version 1.20.1. Happens when I put a phys bearing on a physical object (Tank with rotating turret) and then interact with it. Server continues to work properly without noticeable TPS drops, just the console is unusable. Completely destroying everything attached to the phys bearing and restarting the server fixes the outputs. Installing VMod didn't solve the problem. Interactive isn't installed

**Comment by blockninja124** [comment]
@sleepsemek are you on the latest Valkyrien Skies (Beta.7)? Just to make sure this bug is still present in the absolute latest version.

**Comment by sleepsemek** [comment]
> [@sleepsemek](https://github.com/sleepsemek) are you on the latest Valkyrien Skies (Beta.7)? Just to make sure this bug is still present in the absolute latest version.

Yep, Beta.7, forge-47.2.20

**Comment by sleepsemek** [comment]
I tried to reproduce the bug with the exact same setup in a fresh singleplayer world, but apparently, the error only occurs on the server.
In the console, I only see two ShipIds repeating constantly: 281 and 279. I deleted the specific ship I was interacting with when this bug occured and started building an identical ship from scratch. This time, when I interacted with copycat+ blocks, the console started spamming the exact same two ShipIds: 281 and 279 again. This time it even triggered a VS physics thread crash, with the error: 'tried creating rigid body from ship with UUID 279, but a rigid body already exists for this ship'.

I have no idea why this new ship is spamming these two specific ShipIds. No other ship on server causes this behavior. I'm also unsure if this is just corrupted server world files, or copycat+ incompatibility, the same ship with create: connected copycat blocks doesn't seem to trigger this bug

**Comment by TheRed928** [comment]
Bump. 

I am running the Tank Tussle 4 modpack [[discord here](https://discord.gg/9uJycpSnhP)] and I am receiving this issue also. My game runs fine then crashes abruptly then shows a log spammed with:
`[21:00:28] [Server thread/WARN] [or.va.co.im.sh.Ak/]: Received physics frame update for ship with ShipId: #####, but a ship with this ShipId does not exist!`
Is there a band-aid mod I could add to fix this?

**Comment by blockninja124** [comment]
What version of Valkyrien skies?

**Comment by TheRed928** [comment]
The modpack has version `2.3.0-beta.9tt2x5+19274981d7` in it.

**Comment by blockninja124** [comment]
We don't officially support that version as it's been modified by Tank Tussle. Also I highly doubt this message is related to your crash, it's a generic warning message. 

I recommend asking for help in the tank tussle discord for help with their modpack and VS version.

**Comment by TheRed928** [comment]
Gotcha. Thank you for your time and help!
