### ISSUE TITLE
a MAJOR issue that impacts most mods

### ISSUE THREAD

**Issue by kirieshkasom** [ValkyrienSkies/Valkyrien-Skies-2#1144]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [x] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Issue description

Sometimes the logs say something along the lines of "the box is too big. returning an empty list; this might break things" and it does break. I'm not sure where to look for cause, but the broken method is: ServerWorld.getEntitiesByClass(Class<Entity> entity, Box box, lambda thing)

Specifically, the box part is impacted. I am not sure how, but it always makes the box bigger than it is. I was very surprised when I found out that it was related.

I'll try to find the cause when I get home, and I'll make a pull request.

### Issue reproduction

1. Have Valkyrien Skies installed.
2. Invoke the "ServerWorld.getEntitiesByClass(args)" method.
3. Check the logs to see that it was broken, and that it returned an empty list.

**Comment by kirieshkasom** [comment]
It seems that the causing mixin is inside vs-core, therefore I cannot find the cause of the problem. I will try to make a fix for this though.

**Comment by kirieshkasom** [comment]
After removing get_entities.MixinLevel from the mixin list, the problem is fixed. I'm not sure if this qualifies as a fix, but it's a temporary one until y'all patch this (this is found in parts not available to public)

For server owners, if you want to have this fixed, open the .jar file as a zip, and locate the "valkyrienskies-common.mixins.json" file. In the massive list, find "feature.get_entities.MixinLevel" and remove it. Save and quit.
P.S. I DO NOT encourage you to do this, as I myself don't understand the extent of the problem, since I don't have any sources.

**Comment by kirieshkasom** [comment]
So after further testing, there seem to be no issues when I override isCollisionBoxToBig to always output false. So, safe to say, it's an easy fix.

**Comment by PriestOfFerns** [comment]
IsCollisionBoxTooBig is a method made to detect when a mod tries to create an AABB with a point in the shipyard and a point in the world, which leads to enormous AABBs with lengths of millions of blocks.

Disabling the method doesn't really fix the core issue — you're just kicking the can further down the road. I can't say for certain, but I imagine removing the method could lead to game crashes with the right kind of mod conflict.

**Comment by kirieshkasom** [comment]
Got it, thanks. But then why is the range so small? Usually the error reports a 3000 to 20000 block radius call, and that's actually what most mods do, hence the issue. I don't know how are the boxes usually that big, but somewhere down the line of the getEntitiesOfClass method the box is made bigger. I have tested this with most popular mods, and usually they have a failsafe for this kind of stuff. This is an easy fix, and I have done it myself already (made a mod), but I can't publish any files except .txt ones, and this shouldn't require a fix mod.

**Comment by kirieshkasom** [comment]
```
public final boolean isCollisionBoxToBig(@NotNull Box aabb) {
      Intrinsics.checkNotNullParameter(aabb, "aabb");
      return aabb.getXLength() > 1000.0D || aabb.getYLength() > 1000.0D || aabb.getZLength() > 1000.0D;
   }
```

I didn't think of decompiling the class with Vineflower (since it's kotlin), so this is the stub I got. This is most likely not correct, but at least I know the values. 

It should be pretty easy to fix this. If a mod were to access a block from the shipyard, the distance would be way bigger. A temporary fix would just be making the boundary higher, like 100000 blocks. For a better fix, the check should refer to the shipyard's location.

**Comment by FlikeID** [comment]
> I already fixed this issue in the latest dev version.

Don't  think  so.
i use 2.3.0.beta10, and stil has this problem. 
When i flying on 10 by 10 ship:

<img width="480" height="251" alt="Image" src="https://github.com/user-attachments/assets/e9de80c1-3b86-46cc-a2bb-f67cc3f1e283" /> (this one)

i have a lot of "the box is too big. returning an empty list; this might break things" and it's stop physic thread for a second.

So, i tried delete "feature.get_entities.MixinLevel from "valkyrienskies-common.mixins.json" file. And it's "fixed". Now i can controll my ship well.  
and it's fix another problems:
1) "the box is too big" problem -- it's just gone
2) step sound problem. don't know  why, but i can't hear footstep on ship's. khow, it's finally not THAT quiet
3) long render time. I play with 32 chunks and i need 10-30 seconds until ship gonna render. I thinked it's ok, but now i need only 2-7 second (chunk distanst matter)
4) huge ram consumation. Like VERY HUGE. I run server with 16 GB of RAM. And i play solo or duo. And it's very common issue for me, when sever shut downing because out of memmory. It's common like minecraft rain.
BUT NOW. Bro 6-8 gb ram. It's miracle. @kirieshkasom Just thank you very much. U save me.

when i delete this mixins, i have only 1 problem: instead of "the box is too big" , i have "i can find mixin T_T" spam, but who actually care.

And ofc i have ~250 mods, who made 1000 incompatibility, but i can handle it, don't worry

I gonna make full bug report on the weekend, @Rubydesic wait for this. I gonna record this problems on video

**Comment by blockninja124** [comment]
Thats interesting, we'll have to examine MixinLevel.

But for 2., do you have "Sound Physics Remastered"? It breaks sounds on ships.
