### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Mr-LemonLime** [ValkyrienSkies/Valkyrien-Skies-2#678]
### This issue occurs when only Valkyrien Skies and addons are installed and no other mods

- [X] I have tested this issue and it occurs when no other mods are installed

### Minecraft Version

1.16

### Mod Loader

Forge

### Issue description

After turning on and off a contraption, the Interactive mod causes a memory leak with console spam of "Received physics frame update for ship with ShipId: X, but a ship with this ShipId does not exist!" with X of course being a number. 

### Issue reproduction

either downloads trios cobble gen: https://youtu.be/zOBmCCofEsM?si=nvv3eABPGE8KGjlf
or make any contraption that turns on and off, such as a minecart contraption with a block above it and have a timer that turns on and off quickly

### Logs

[latest.log](https://github.com/ValkyrienSkies/Valkyrien-Skies-2/files/13836296/latest.log)

**Comment by ahykono** [comment]
I apparently have the same issue so I released a video on it from my survival world https://youtu.be/sCIzS3mQ9JQ
Using a cobblestone generator, console log gets spammed a lot

**Comment by Theuntextured** [comment]
I'm having the same issue on 1.20.1 (latest version of the mod). All I have in my world is a gantry carriage with some drills. No other moving contraption.

**Comment by izeek182** [comment]
I have also encountered this issue, it seems to be related to losing tile entities. I am on ATM 9 1.20.1. After an analysis of a heap dump I found that tile entities in the Everbright have hundreds to hundreds of thousands of copies, all with the same block pos.

**Comment by blockninja124** [comment]
Got fixed in interactive 1.1.1

**Comment by SystemPASCAL** [comment]
I'm using the create: interactive 1.2.1 and VS 2.4.10 with create 6.0.8 for forge 1.20.1 (47.4.10) and it "crashes" (freezes), when turning a assembled interactive train with tuning the tracks. When checking the log data, it states the same error message multiple times (sometimes minecraft freezes shortly, sometime it freezes compleatly).

**Comment by blockninja124** [comment]
do you have the mod "create: threaded trains"

**Comment by SystemPASCAL** [comment]
no, it's not part of my modpack. 

The mods i'm using is Copycat 3.0.4, create: connected 1.1.13, create individual train speed 1.0.0, create big cannons 5.11.2, create liquid fuel 2.1.1, fluid 1.2.3, just enough items, kotlinforforge 4.12.0, ritchiesprojectilelib 2.1.1, skinlayers3d, Steam N'Rails 1.7.2 and Vs Hoseconnectors 0.0.9 additionally to the mods mentioned before.

The only mods i can think of, that maybe cause the problem is Steam N'Rails or create individual train speed. Maybe create: connected, but that does not changes anything special about trains or the tracks.

**Comment by SystemPASCAL** [comment]
I just tested it with only create: interactive 1.2.1, VS 2.4.10, kotlinforforge 4.12.0 and create 6.0.8 for forge 1.20.1 (47.4.10) and it still freezes when trying it. The error message in the log stays the same aswell (Received physics frame update for ship with ShipId: X, but a ship with this ShipId does not exist! (X as an number (changes each time, although using the same train and same setup)))

**Comment by blockninja124** [comment]
can you send a video of you causing the freeze?
Also I'm not reopening the issue because your bug is not a memory leak, its just a plain old freeze.

**Comment by SystemPASCAL** [comment]
It seems like i cannot upload the video here in this comment (probably because of its file size), but i can upload the log. It contains actually three problems: the first one was a 5-10 second freeze when creating a normal train (with a visual glitch at the end) (might be related to the freezing problem) and then another when rotating the train the first time (shortly freezes) with the result, that after it stops, the train disapears visually. The third one is later in the log, when making the train into a interactive train, and rotating it then (freezes compleatly). 

In the video, I also show some other data, that might help and how i fixed the first problem momentarly ingame, so if you have an idea on how to share it, then i can show it to you too.

[latest.log](https://github.com/user-attachments/files/26852844/latest.log)

Edit: The freez might be related to the graphics, but it is still strange and never happend before. The visual glitch happend before with VS: clockworks, which is why i knew, how to fix it, but it happend before because of inuficent Memory. That should not be the case now (16 GB for Minecraft with forge)
